openapi: 3.0.3
info:
  title: TANIATOR API
  version: 1.0.0
servers:
  - url: http://localhost:8000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/product:
    $ref: 'paths/product.yaml'
  /api/biedronka/token:
    $ref: 'paths/biedronka/token.yaml'
  /api/biedronka/login:
    $ref: 'paths/biedronka/login.yaml'
  /api/users/register:
    $ref: 'paths/user/register.yaml'
  /api/users/login:
    $ref: 'paths/user/login.yaml'
  /api/product_history:
    $ref: 'paths/product_history.yaml'
